baseURL = "http://example.org/"
languageCode = "en-us"
title = "The Palest Ink"
theme = "mainroad"
paginate = "5"

[Author]
    name = "Steven Klassen"
    bio = "Teaching SolarWinds new tricks since 2007; he/him; husband to @mrsxinu; daddy to Mackenzie; gopher; orthographist."

[Params]
    subtitle = "... is better than the best memory." # Subtitle of your site
    description = "Bits and pieces of experience I've acculumated along the way." # Description of your site
    authorbox = true
    toc = true
    post_navigation = true
    postSections = ["posts"] # the section pages to show on home page and the "Recent articles" widget

[Params.sidebar]
    home = "right"
    list = "left"
    single = false
    widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets.social]
    facebook = "mrxinu"
    twitter = "mrxinu"
    instagram = "mrxinu"
    linkedin = "mrxinu"
    github = "mrxinu"
    email = "sklassen@gmail.com"
