baseURL = "https://mrxinu.com/"
languageCode = "en-us"
title = "The Palest Ink"
theme = "mainroad"
paginate = "5"
pygmentsCodeFences = true
pygmentsStyle = "trac"

[Author]
    name = "Steven Klassen"
    bio = "Teaching SolarWinds new tricks since 2007; he/him; husband to @mrsxinu; daddy to Mackenzie; gopher; orthographist."

[Params]
    subtitle = "... is better than the best memory." # Subtitle of your site
    description = "Bits and pieces of experience I've acculumated along the way." # Description of your site
    post_meta = ["date", "categories"]
    post_navigation = true
    authorbox = true

[Params.sidebar]
    home = "right"
    widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets.social]
    twitter = "mrxinu"
    linkedin = "mrxinu"
    github = "mrxinu"
    email = "sklassen@gmail.com"
