baseurl = "/"
title = "My Blog"
theme = "ghostwriter"

[Author]
    name = "Steve Klassen"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "The Palest Ink"
    description = "... is better than the strongest memory."
    github = "https://github.com/mrxinu"
    twitter = "https://twitter.com/mrxinu"
    email = "sklassen@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
