baseURL = "https://mrxinu.com/"
languageCode = "en-us"
title = "The Palest Ink"
theme = "mainroad"
paginate = "5"
pygmentsCodefences = true
pygmentsStyle = "pygments"

[Author]
    name = "Steven Klassen"
    bio = "Passionate about teaching folx what I know; @mrsxinu's mate; Mackenzie's dad; collector of languages. He/Him"

[Params]
    subtitle = "... is better than the best memory." # Subtitle of your site
    description = "Bits and pieces of experience I've acculumated along the way." # Description of your site
    post_meta = ["date", "categories"]
    post_navigation = true
    authorbox = true

[Params.sidebar]
    home = "right"
    widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets.social]
    twitter = "mrxinu"
    linkedin = "mrxinu"
    github = "mrxinu"
    email = "sklassen@gmail.com"
